### ISSUE TITLE
Arrow Drawing Does Not Print

### ISSUE THREAD

**Issue by ollielau** [county-of-simcoe-gis/SimcoeCountyWebViewer#16] opened 2019-10-28 13:52 UTC
@Saspect-IO

It seems as though the arrow drawing either doesn't allow exports to print, or when it does, it does not show up. I have tested this with PNG, PDF, and JPG outputs, with Topo/Imagery, with different settings for exports, and with different arrows. In most cases there is a print error, and in very few cases does the map actually export to something, and when it has, the arrow has not been present.

![image](https://user-images.githubusercontent.com/56846925/67683954-ae6ffa80-f968-11e9-8a8c-a5a6154076ab.png)

**Comment by nhellas** [comment] 2019-10-29 20:13
Suggest this is a duplicate of [Issue 15](https://github.com/county-of-simcoe-gis/SimcoeCountyWebViewer/issues/15)

**Comment by iquitwow** [comment] 2019-10-30 12:27
Will close this once #15 get resolved.

**Closed** 2019-11-05 14:10 UTC
Labels: duplicate
