### ISSUE TITLE
Basemaps (under Topo ) are not clickable  - iPhone Mobile Access

### ISSUE THREAD

**Issue by oren-ned** [county-of-simcoe-gis/SimcoeCountyWebViewer#48] opened 2020-04-16 03:17 UTC
opengis.simcoe.ca: Basemaps options (under Topo ) are not clickable on iPhone 6s - Software version 13.3.1.

**Comment by iquitwow** [comment] 2020-04-21 14:57
@oren-ned  I don't have access to an iPhone 6 to debug the styling.  Is something you or @reed-tom can look at?

**Comment by reed-tom** [comment] 2020-04-21 15:16
looks like it's the same on all mobile devices, I was able to reproduce the issue using chrome's mobile layout.

If you set the z-index to anything greater than 0 for the sc-basemap-topo-container css class it appears to fix the issue.

I'm not sure what this override was put in to fix, but I'd guess this is caused by the OLOverride.css
  .ol-overlaycontainer-stopevent {
    z-index: 1 !important;
  }

**Comment by iquitwow** [comment] 2020-04-21 18:43
daa0a9af7e6a291c8b367d6131a7d28c97326c46 Thanks Tom.  Pushed the fix.  Simple zIndex change to 2 on the topo popup container.

**Closed by iquitwow** 2020-04-21 18:43 UTC
